# Generated by Django 3.0.8 on 2021-05-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaliser',
            name='numero_lit',
            field=models.IntegerField(),
        ),
    ]
