# Generated by Django 3.0.8 on 2021-05-06 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0003_auto_20210506_0001'),
        ('hopital', '0002_auto_20210505_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salle',
            name='nom_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salle_service', to='personne.Service'),
        ),
        migrations.AlterField(
            model_name='salle',
            name='numero_salle',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
