# Generated by Django 3.0.8 on 2021-05-06 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0005_maladie'),
        ('hopital', '0003_auto_20210506_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaliser',
            name='nom_maladie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitaliser_maladie', to='personne.Maladie'),
        ),
        migrations.DeleteModel(
            name='Maladie',
        ),
    ]
