# Generated by Django 3.0.8 on 2021-05-06 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0004_auto_20210506_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salle',
            name='nom_infermier',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='nom_service',
        ),
        migrations.DeleteModel(
            name='Hospitaliser',
        ),
        migrations.DeleteModel(
            name='Salle',
        ),
    ]
