# Generated by Django 3.0.8 on 2021-05-05 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(max_length=20)),
                ('nom', models.CharField(max_length=50)),
                ('tel', models.IntegerField(max_length=8)),
                ('adresse', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Docteur',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personne.Personne')),
                ('specialite', models.CharField(max_length=50)),
            ],
            bases=('personne.personne',),
        ),
        migrations.CreateModel(
            name='Infermier',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personne.Personne')),
                ('rotation', models.CharField(max_length=50)),
                ('salaire', models.FloatField(max_length=8)),
            ],
            bases=('personne.personne',),
        ),
    ]
