# Generated by Django 3.0.8 on 2021-07-04 23:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('tel', models.IntegerField()),
                ('adresse', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('nom_service', models.CharField(max_length=20)),
                ('batiment', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Docteur',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personne.Personne')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docteur_specialite', to='personne.Specialite')),
            ],
            bases=('personne.personne',),
        ),
        migrations.CreateModel(
            name='Infermier',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personne.Personne')),
                ('rotation', models.CharField(max_length=50)),
                ('salaire', models.FloatField()),
            ],
            bases=('personne.personne',),
        ),
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personne.Personne')),
                ('date_entree', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=('personne.personne',),
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_salle', models.IntegerField()),
                ('nom_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salle_service', to='personne.Service')),
                ('nom_infermier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salle_infermier', to='personne.Infermier')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='directeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directeur_service', to='personne.Docteur'),
        ),
        migrations.AddField(
            model_name='infermier',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infermier_service', to='personne.Service'),
        ),
        migrations.CreateModel(
            name='Hospitaliser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lit', models.IntegerField()),
                ('diagnostic', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('nom_salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitaliser_salle', to='personne.Salle')),
                ('nom_maladie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitaliser_maladie', to='personne.Maladie')),
            ],
        ),
    ]
