# Generated by Django 3.0.8 on 2021-07-05 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaliser',
            name='nom_salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitaliser_salle', to='personne.Salle', verbose_name='Numero salle'),
        ),
    ]
