# Generated by Django 3.0.8 on 2021-05-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infermier',
            name='salaire',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='personne',
            name='num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personne',
            name='tel',
            field=models.IntegerField(),
        ),
    ]
