# Generated by Django 3.0.8 on 2021-05-06 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0002_auto_20210505_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('nom_service', models.CharField(max_length=20)),
                ('batiment', models.CharField(max_length=20)),
                ('directeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directeur_service', to='personne.Docteur')),
            ],
        ),
        migrations.AddField(
            model_name='infermier',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='infermier_service', to='personne.Service'),
            preserve_default=False,
        ),
    ]
