# Generated by Django 3.0.8 on 2021-05-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0003_auto_20210506_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='prenom',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
