# Generated by Django 3.0.8 on 2021-05-06 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0005_maladie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_salle', models.IntegerField()),
                ('nom_infermier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salle_infermier', to='personne.Infermier')),
                ('nom_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salle_service', to='personne.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Hospitaliser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lit', models.IntegerField()),
                ('diagnostic', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('nom_maladie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitaliser_maladie', to='personne.Maladie')),
                ('nom_salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitaliser_salle', to='personne.Salle')),
            ],
        ),
    ]
