# Generated by Django 3.0.8 on 2021-05-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0006_hospitaliser_salle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maladie',
            name='date_entree',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
