# Generated by Django 3.0.8 on 2021-05-06 00:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0007_auto_20210506_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maladie',
            name='date_entree',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
